# Generated by Django 4.2.13 on 2024-07-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_alter_chatmessage_project_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='project_request',
        ),
    ]
