# Generated by Django 4.2.13 on 2024-07-11 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_projectrequest_remove_project_client_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default=datetime.datetime(2024, 7, 11, 13, 27, 59, 643318, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
