# Generated by Django 4.2.13 on 2024-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0011_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='milestone_images/'),
        ),
    ]
