# Generated by Django 4.2.13 on 2024-07-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0012_milestone_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
