# Generated by Django 4.2.13 on 2024-07-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buniwa', '0047_alter_profile_options_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
